# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 🌎 Adolfo Andres Hincapie
subtitle: Personal web-site
email: "aahincap@unal.edu.co"
logo: "/assets/images/88x88.png"
teaser: "/assets/images/500x300.png"
description: >- # this means to ignore newlines until "baseurl:"
  Forestry, Anthropologist, Spatial Analyst, and Modeler of Environmental and Social Systems. 
  Interested in: Ecosystem Services Market, Tools to unlock Natural-Based Solutions
twitter_username: "@_geocaptain"
github_username: aahincapie
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Bogota # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Andres Hincapie"
  avatar : "/assets/images/bio-photo_bw.jpg"
  bio    : "Forestry, Anthropologist, Spatial Analyst, and Modeler of Environmental and Social Systems. Interested in: Ecosystem Services Market, Tools to unlock Natural-Based Solutions. Also an intelligent coffee drinker, landowner small-farm-lab **La Montaña Azul**. My waste time is spent hiking, riding moto, trying with indoor planting(farmer), and making furniture featuring wood(carpenter)."
  location  : "Medellin, Colombia"
  email  : "aahincap@unal.edu.co"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://aahincapie.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_geocaptain"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aahincapie"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/aahincapie/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_geocaptain"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/aahincapie"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/_geocaptain/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
